services:
    nginx:
        build:
            dockerfile: ./docker-configs/nginx/Dockerfile
        ports:
            - "88:80"
        volumes:
            - ./docker-configs/nginx/sign.jwt.rsa.conf:/etc/nginx/conf.d/default.conf
            - /www/sign-jwt-rsa:/local
    php:
        build:
            dockerfile: ./docker-configs/php/Dockerfile
        volumes:
            - /www/sign-jwt-rsa:/local
